name: laraveltest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.2.4
  connectivity_plus: 1.0.6
  flutter: 
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

